### PR TITLE
Fix merging environment variables on Windows

### PR DESCRIPTION
**Pull request by dpomier**
Fix vshaxe/vshaxe#482 and vshaxe/vshaxe#486 by preserving the casing of the initial keys, as suggested in https://github.com/HaxeFoundation/haxe/issues/10151#issuecomment-789579064.

### CODE REVIEW

**Comment by kLabz** [comment]
https://github.com/vshaxe/haxe-language-server/blob/fb0cb23236dd4ad6d0611f2902bf71cdda85eb1f/src/haxeLanguageServer/server/HaxeServer.hx#L88

`for (initialKey in to.keys())` maybe ?

**Comment by dpomier** [comment]
> I'm curious how exactly you managed to reproduce the problem.

It's a bit un-straightforward, I had to play with my PATH values. The configuration I ended up getting is as follow:
- My PATH is written "Path" in the system environment variables,
- and contains at the first position "path/to/haxe"
- and at the last position "path/to/neko", but I'm not sure this makes a difference.
- the Haxe project uses Lix and ".haxerc" is configured with:
```json
{
  "version": "path/to/haxe",
  "resolveLibs": "scoped"
}
```
In my case all libraries are installed with Lix, and not globally via `haxelib`.

**Comment by Gama11** [comment]
Oh, a haxerc with a path to Haxe... That might explain why I could reproduce this a while ago, but not recently. I haven't built Haxe from source for some time and thus haven't had a need for that feature.

**Comment by Gama11** [comment]
@dpomier Big thanks for looking into and fixing this, considering it wasn't even caused by your changes after all. 😅

**Pull request merged**
