### PR TITLE
Fix definition preview

### PR DESCRIPTION
**Pull request by RblSb**
Closes https://github.com/vshaxe/vshaxe/issues/530

Cause: https://github.com/microsoft/vscode/commit/1d7f8442aaa3965aa8212b9dda53d9362b08d423

### CODE REVIEW

**Comment by Gama11** [comment]
How did you figure out it was that VSCode commit that caused it?

**Comment by RblSb** [comment]
Previously released vshaxe version stops showing me definition preview on 1.67, but on 1.66 things are working. I can be wrong about commit, but there is no much other commits about this feature (i found it by googling ctrl+hover implementation in vscode github, and then checked latest history for file).
This change went unnoticed because most extension are migrated to `DefinitionLink`, i think.

**Comment by Gama11** [comment]
I'm asking because from the commit message it sounds like it might've been unintentional - if it really was "dead code", it shouldn't change the behavior.

**Comment by RblSb** [comment]
I made report in vscode repo, before i found in docs that `DefinitionLink` is prefered way to handle definition provider.
https://github.com/microsoft/vscode/issues/152279

**Pull request merged**
