### PR TITLE
Fix case colon completion

### PR DESCRIPTION
**Pull request by RblSb**
Ported from legacy server. Still legit?
Also closes https://github.com/HaxeFoundation/haxe/issues/9311

### CODE REVIEW

**Comment by Gama11** [comment]
Doesn't seeem right to fix this here...

**Comment by RblSb** [comment]
If only we know where to fix it... I think this happens because of `triggerCharacters`, not sure how it can be filtered by context or something. But asking for completion right after colon in `case _:|` is very annoying for sure.

**Comment by Gama11** [comment]
I'd have to look into this in more detail, I don't remember all the logic behind this. My initial thinking was that the compiler is still returning some results here when it shouldn't, but your screenshot shows snippet completion which is from the language server, so maybe something is needed on the server-side after all.

Either way, using a regex for detection here isn't robust, we have the token tree nowadays that could be used instead.

**Comment by RblSb** [comment]
I found a reason:
https://github.com/vshaxe/haxe-language-server/blob/6efc0b9a673983b4546a208ae1adc19ff6af25d9/src/haxeLanguageServer/features/haxe/completion/CompletionFeature.hx#L194

**Pull request closed without merging**
