### PR TITLE
Fix signature hints for functions without documentation

### PR DESCRIPTION
**Pull request by RblSb**
Fix for latest protocol implementation in vscode...
Seems like regression in it, tho, so i not sure what to do.

### CODE REVIEW

**Comment by Gama11** [comment]
What do you mean by "fix", what happens if null is returned?

This might be related to the vscode-languageclient update? Might be worth reporting there.

**Comment by RblSb** [comment]
You dont get signature hint when documentation property is null, maybe because of implementation unification with `textDocument/completion` type, where `documentation` should be filled:
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion
Not sure where to report it, and can you reproduce it on git vshaxe?

**Comment by RblSb** [comment]
Should be good now, see:
https://github.com/microsoft/vscode-languageserver-node/issues/966#issuecomment-1141185577
This is problematic type hole in our externs for vscode case, but eh.

**Comment by AlexHaxe** [comment]
> This is problematic type hole in our externs for vscode case, but eh.

I guess we have to remember to treat every optional field like that to be on the safe side.

**Pull request merged**
