### PR TITLE
Improve toplevel sorting

### PR DESCRIPTION
**Pull request by RblSb**
Some implementation.

Closes https://github.com/vshaxe/vshaxe/issues/518

### CODE REVIEW

**Comment by Gama11** [comment]
Not sure about using empty string as a "no value", null seems more explicit?

**Comment by RblSb** [comment]
Because of vscode limitations, there is no openEditor/changeEditor events if you reopen vscode app and it will reopen previous project with some editor (probably Haxe server does not catch this so early).
That latest package field by default means "empty package", and it will be used for reopened project editor (before you change tab) and root (src) classes. Using `null` for "reopen corner-case" seems unnecessarily, since logic is not different.
And this limitation is probably fine, you only lose order of same-package items before you swap tab.

There is project to test writing `Array / Audio / Button / etc` in different `Main.hx` files:
[meh_imports.zip](https://github.com/vshaxe/haxe-language-server/files/8344081/meh_imports.zip)

**Comment by RblSb** [comment]
Something to do?
Also, for some reason building extension + vscode restart does not change vshaxe globally, only for debug sessions, does custom installation is only possible with `vsce package`?

**Comment by AlexHaxe** [comment]
> Also, for some reason building extension + vscode restart does not change vshaxe globally, only for debug sessions, does custom installation is only possible with `vsce package`?

yeah, for a debug session vscode seems to setup a special environment so that you can debug extensions without overwriting or interfering with installed versions.

I usually symlink my development version into vscode's extension folder so I can have both, but that only works on unix. last I checked Windows doesn't support that, or at least not in a way that works with vscode. 
also: putting your dev folder inside vscode's extension folder is a bad idea, since vscode will wipe it when it updates to a new version of that extension.

**Pull request merged**
