### PR TITLE
Fix LSP for documents with surrogates pairs

### PR DESCRIPTION
**Pull request by kLabz**
Currently, Haxe LSP doesn't work well with surrogate pairs:

Recording 2023-01-24 at 11 58 31

Fixes https://github.com/vshaxe/vshaxe/issues/546
Fixes https://github.com/vshaxe/vshaxe/issues/343

* [x] Fix completion requests after surrogate pairs
* [x] Fix hover requests after surrogate pairs
* [x] Fix hover requests after surrogate pairs (same line)
* [x] Fix hover requests _including_ surrogate pairs 
* [x] Don't let diagnostics break above two points...
* [x] Identify and fix other kind of requests (go to definition, find references, etc.)
* [x] Double check that Haxe LSP still works fine with other kind of documents, and Haxe 3.x

Current state with this PR:

Recording 2023-01-24 at 16 46 43

### CODE REVIEW

**Comment by Gama11** [comment]
> When there are too many of these characters the positions start being offset a bit;

Why's that?

**Comment by kLabz** [comment]
Not sure yet; I'd need to recover a few neurons and try to figure out what's going wrong.
Note that it only happens on the line with such characters, and only for hover requests.
Recording 2023-01-24 at 17 48 51

**Comment by kLabz** [comment]
Fixed that issue:

Recording 2023-01-24 at 22 09 57

**Comment by RblSb** [comment]
Also fixes https://github.com/vshaxe/vshaxe/issues/343?

**Comment by kLabz** [comment]
Yup !

**Pull request merged**
