### PR TITLE
sync with Haxe regarding completion item filtering

### PR DESCRIPTION
**Pull request by Simn**
For https://github.com/HaxeFoundation/haxe/pull/8642

Not sure how to handle the transition here...

### CODE REVIEW

**Comment by Gama11** [comment]
By transition, you mean compatibility with earlier Haxe 4 versions?

I'd simply check if `index` / `isIncomplete` are `null` and if so, respectively fall back to the old method of doing things. Technically this is probably also the sort of change that should increase that protocolVersion Haxe sends...

Looks like the max amount of items is not configurable via Initialize yet?

**Comment by Simn** [comment]
It is but I forgot to update the Haxe type. I'll change it so filtering only happens if a max amount is set by the IDE.

**Comment by Simn** [comment]
Regarding transition, what's our policy regarding _compiling_ vshaxe? Because that will require the latest Haxe version if we depend on the `isIncomplete` and `index` fields from Haxe std. If we don't care about this then it's not a problem.

**Comment by Gama11** [comment]
We just need to update the Haxe version in `.haxerc` once the Haxe nightly build is through for CI to pass.

**Pull request merged**
